extends Node
## All audio: music themes, biome ambience, SFX pool and the procedural-feel
## engine voice. Audio files are pre-rendered loops generated by
## tools/gen_audio.py (pure-python synth) — zero runtime DSP cost on mobile.

const SFX_POOL_SIZE := 4

var _bus_volumes: Dictionary = {}
var _sfx_streams: Dictionary = {}
var _sfx_pools: Dictionary = {}
var _music: AudioStreamPlayer
var _ambience: AudioStreamPlayer
var _engine: AudioStreamPlayer
var _engine_pitch: float = 0.8
var _current_theme: String = ""
var _current_ambience: String = ""
var _theme_enabled: bool = true
var _started: bool = false

const SFX_FILES: Dictionary = {
	"coin": "res://assets/audio/sfx_coin.wav",
	"pop": "res://assets/audio/sfx_pop.wav",
	"fuel": "res://assets/audio/sfx_fuel.wav",
	"click": "res://assets/audio/sfx_click.wav",
	"hover": "res://assets/audio/sfx_hover.wav",
	"whoosh": "res://assets/audio/sfx_whoosh.wav",
	"land": "res://assets/audio/sfx_land.wav",
	"crash": "res://assets/audio/sfx_crash.wav",
	"flip": "res://assets/audio/sfx_flip.wav",
	"unlock": "res://assets/audio/sfx_unlock.wav",
	"best": "res://assets/audio/sfx_best.wav",
	"beep": "res://assets/audio/sfx_beep.wav",
	"go": "res://assets/audio/sfx_go.wav",
	"sad": "res://assets/audio/sfx_sad.wav",
	"cash": "res://assets/audio/sfx_cash.wav",
	"denied": "res://assets/audio/sfx_denied.wav",
	"tick": "res://assets/audio/sfx_tick.wav",
	"pennant": "res://assets/audio/sfx_pennant.wav",
}

func _ready() -> void:
	process_mode = ProcessMode.PROCESS_MODE_ALWAYS
	_ensure_buses()
	_music = AudioStreamPlayer.new()
	_music.bus = "Music"
	add_child(_music)
	_ambience = AudioStreamPlayer.new()
	_ambience.bus = "Music"
	_ambience.volume_db = -8.0
	add_child(_ambience)
	_engine = AudioStreamPlayer.new()
	_engine.bus = "Engine"
	add_child(_engine)
	var eng: AudioStream = load("res://assets/audio/engine_loop.wav")
	if eng:
		_make_loop(eng)
		_engine.stream = eng
		_engine.play()
	_engine.volume_db = -80.0
	_build_sfx_pool()
	_apply_volumes()
	EventBus.settings_changed.connect(_on_settings_changed)

func _ensure_buses() -> void:
	for bus in ["Music", "SFX", "Engine"]:
		if AudioServer.get_bus_index(bus) < 0:
			AudioServer.add_bus()
			var idx := AudioServer.bus_count - 1
			AudioServer.set_bus_name(idx, bus)
			AudioServer.set_bus_send(idx, "Master")
	_apply_volumes()

func _make_loop(st: AudioStream) -> void:
	# AudioStreamWAV loop modes: 0 disabled, 1 forward, 2 ping-pong, 3 backward.
	st.loop_mode = 1
	st.loop_begin = 0
	st.loop_end = -1


func _build_sfx_pool() -> void:
	for key in SFX_FILES:
		var stream: AudioStream = load(SFX_FILES[key])
		_sfx_streams[key] = stream
		var pool: Array = []
		for i in SFX_POOL_SIZE:
			var p := AudioStreamPlayer.new()
			p.bus = "SFX"
			p.stream = stream
			add_child(p)
			pool.append(p)
		_sfx_pools[key] = pool

func play_sfx(id: String, pitch_jitter: float = 0.0) -> void:
	var pool: Array = _sfx_pools.get(id)
	if pool == null or _sfx_streams.get(id) == null:
		return
	var p: AudioStreamPlayer = pool[randi() % pool.size()]
	p.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	p.play()

func play_theme(theme_id: String) -> void:
	if theme_id == _current_theme:
		return
	_current_theme = theme_id
	if not _theme_enabled:
		_music.stop()
		return
	var path := "res://assets/audio/%s.wav" % theme_id
	var stream: AudioStream = load(path)
	if stream == null:
		return
	_make_loop(stream)
	_music.stream = stream
	_music.play()

func stop_theme() -> void:
	_current_theme = ""
	_music.stop()

func set_ambience(id: String) -> void:
	if id == _current_ambience:
		return
	_current_ambience = id
	if id.is_empty():
		_ambience.stop()
		return
	var stream: AudioStream = load("res://assets/audio/%s.wav" % id)
	if stream == null:
		return
	_make_loop(stream)
	_ambience.stream = stream
	_ambience.volume_db = -80.0
	_ambience.play()
	var tw := create_tween()
	tw.tween_property(_ambience, "volume_db", -8.0, 1.5)

func set_engine(rpm: float, throttle: float, on: bool) -> void:
	if not on:
		_engine.volume_db = lerpf(_engine.volume_db, -80.0, 0.2)
		return
	_engine_pitch = lerp(_engine_pitch, clampf(rpm, 0.2, 2.2), 0.15)
	_engine.pitch_scale = _engine_pitch
	var target: float = lerpf(-42.0, -8.0, clampf(throttle, 0.0, 1.0))
	_engine.volume_db = lerpf(_engine.volume_db, target, 0.2)

func set_music_muted(muted: bool) -> void:
	_theme_enabled = not muted
	if muted:
		_music.stop()

# ------------------------------------------------------------------ volumes
func _apply_volumes() -> void:
	var mv: float = float(SaveManager.read("settings.music_volume", 0.8))
	var sv: float = float(SaveManager.read("settings.sfx_volume", 1.0))
	var ev: float = float(SaveManager.read("settings.engine_volume", 0.9))
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Master"), db_from_linear(1.0))
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Music"), db_from_linear(mv))
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("SFX"), db_from_linear(sv))
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Engine"), db_from_linear(ev))

func _on_settings_changed(key: String) -> void:
	if key.begins_with("settings."):
		_apply_volumes()

static func db_from_linear(v: float) -> float:
	if v <= 0.001:
		return -80.0
	return 20.0 * log(v) / log(2.0)
